[theme]
base = "light"
primaryColor = "#0078d4"
backgroundColor = "#f3f2f1"
secondaryBackgroundColor = "#ffffff"
textColor = "#323130"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
